# Generated by Django 4.1.1 on 2022-12-10 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MyEducation', models.CharField(max_length=100)),
                ('MyExperience', models.CharField(max_length=100)),
                ('dateD', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesociete', models.CharField(max_length=100)),
                ('projet', models.CharField(max_length=100)),
                ('dateI', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('niveau', models.IntegerField()),
                ('formation', models.CharField(max_length=100)),
                ('dateS', models.DateField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.language')),
            ],
        ),
    ]
